CONTRIBUTING.md, README.md, infra/pre-commit
Adds a pre-commit hook under a new `infra/` directory that will
automatically format modified Python files with `Black`.
Also fixes a minor typo in the top-level README.
=> Add a pre-commit hook to format code (#45)

ambuda/static/js/main.js, ambuda/templates/htmx/text-section.html, ambuda/templates/include/font-size-options.html
Adds support to change font size of texts.
Mapping of fontsizes supported by Tailwind to the selection available in the menu:
text-base -> Tiny
text-lg -> Small
text-xl" selected>Medium
text-2xl -> Large
text-3xl -> X-Large
=> Add support for different font sizes

.github/workflows/basic-tests.yml, README.md
Address #16.
Runs on pull requests, pushes to main, and manual invocations.
The badge will appear as a broken link until this is run on main. View [this](https://github.com/theFestest/ambuda/actions/workflows/basic-tests.yml/badge.svg?branch=introduce-ci) on my fork to see how it should look instead.
For now its just the python unit tests, but can serve as a model for addition additional lints, code coverage reports, etc. Let me know if you intended the initial CI to include anything else.
View the "checks" tab under this test PR to see the results. https://github.com/theFestest/ambuda/pull/1
=> Introduce basic CI for python tests.

ambuda/templates/proofing/project.html, ambuda/utils/proofing_utils.py
The functions for xml and plaintext were duplicated, this cleaning
abstracts the duplicated logic. The text box's lack of capitalization
seemed inappropriate next to the full caps of the XML download box.
=> Refactor proofing utils and rename text download box

ambuda/consts.py, ambuda/seed/texts/gretil.py
Importing the text from https://github.com/ambuda-project/gretil/pull/7 
This one corresponds to [this GRETIL text](http://gretil.sub.uni-goettingen.de/gretil/corpustei/transformations/html/sa_kulazekhara-mukundamAlA-eddurgaprasad.htm) (from [book](https://archive.org/details/Kavyamala_anthology_series_of_Nirnaya_sagar_press/KavyamalaAnthologyVol.01-MahaganapatistotraOfRaghavachaitanyaEtc1929/page/n13/mode/2up), 34 verses) and there's [another GRETIL text](http://gretil.sub.uni-goettingen.de/gretil/corpustei/transformations/html/sa_kulazekhara-mukundamAlA.htm) (from [book](https://archive.org/details/RamanujaStotraMala1949/page/n15/mode/2up), 40 verses).
Was initially planning to add both (hence the `-1` in the url/slug), but on second thoughts maybe it's not worth having both of them at …
=> For adding Mukundamala

.github/workflows/basic-tests.yml, ambuda/__init__.py, config.py, scripts/initialize_db.py
All config values are defined and documented on a `BaseConfig` from which all config schemas inherit. Further, I added extra validation checks to ensure that our configs are well-formed.
The one thing I dislike here is that `_env` will happily return None if an environment variable can't be found. It has this behavior (as opposed to just failing) because otherwise, class initialization will fail if a value is defined and we won't be able to import the module.
The workarounds to this that I can think of are clumsy:
- configs in separate modules, dynamically import as needed
- initialize classes in wrapped functions that run only when called
- list all environment variables on `.env` on startup, even if they're empty strings
Maybe the third one isn't so bad.
=> Add cleaner config setup and comments

scripts/install_from_scratch.sh
Otherwise, I have to set the upload folder manually when starting up ambuda for the first time --
=> Set default FLASK_UPLOAD_FOLDER

ambuda/templates/about/people.html
To recognize Suhas' substantial and ongoing contributions to Ambuda, I'm
adding some information about him to our People page. The "Text Curation
and Sourcing" title sounds a little clumsy, but we can change it later.
=> Add Suhas to about.people

ambuda/templates/proofing/pages/edit.html
This makes an implicit point explicit: our contributions, to the extent
that they have copyright in different jurisdictions, should be dedicated
to the public domain. My understanding is that the digital text that we
produce on Ambuda will thus have the same access permissions as the
original book on which it is based.
=> Add explicit CC0 statement to page edit form

ambuda/tasks/projects.py, config.py, fabfile.py, scripts/check_prod_setup.py
This commit adds some basic checks that test the production setup before
deploying a new instance. If any of these checks fail, we should abort
the deploy.
=> Verify the production setup before deploying

scripts/install_from_scratch.sh
"EOF" must be un-quoted in order for variable substitution to actually be evaluated. Follow-up to https://github.com/ambuda-org/ambuda/pull/87.
=> Fix typo in .env file creation

ambuda/admin.py, ambuda/models/base.py, ambuda/models/proofing.py, ambuda/models/talk.py, ambuda/queries.py, ambuda/tasks/projects.py, ambuda/templates/proofing/projects/admin.html, ambuda/views/proofing/main.py, cli.py, migrations/versions/82cf1fd072bb_add_project_creator_and_timestamps.py, test/ambuda/tasks/test_projects_tasks.py
`creator_id` tracks the project creator for better visibility into the
overall effort. This is nullable for now because we need to manually
migrate the production setup first.
`created_at` is likewise for better visibility, and it can show proofers
which projects have been in progress the longest.
`updated_at` is not useful now, but in the future, it can show proofers
which projects have been changed most recently.
Test plan: unit tests, ran `upgrade` and `downgrade` and `upgrade`
again.
=> Add project creator_id, created_at, and updated_at

ambuda/static/js/main.js, ambuda/templates/base.html, ambuda/templates/htmx/text-block.html, ambuda/templates/htmx/text-section.html, ambuda/views/proofing/tagging.py, ambuda/views/reader/texts.py, ambuda/xml.py, test/ambuda/test_xml.py
All blocks now follow this simple structure:
<s-block id="">
<div class="mula">
</div>
</s-block>
`s-` (for Sanskrit) is our convention for custom elements. We can always
locate the containing block by searching for `closest("s-block")`.
Test plan: unit tests and tried the following tests on local host:
- click word
- click parsed word for dictionary entry
- show original
=> Change HTML structure for text blocks

ambuda/templates/base.html, ambuda/templates/proofing/pages/edit.html
After recent changes for Alpine, this `<textarea>` is no longer
initialized with the server value, which can feel like a bug to end
users.
=> Fix rendering bug for editor textarea

.eslintrc.js
Re-enables no-console eslint rule that was disabled in 9e89bcb293e75938bc35f0877bb26207d213b953.
See https://eslint.org/docs/latest/rules/no-console#options
=> Only allow console.error

.eslintrc.js, ambuda/static/js/dictionary.js, ambuda/static/js/main.js, ambuda/static/js/reader.js, ambuda/templates/dictionaries/index.html, ambuda/templates/header-main-footer.html, ambuda/templates/texts/section.html
We now have three applications:
- `dictionary.js`, which implements the standalone dictionary tool.
- `proofreading.js`, which implements the proofing UI.
- `reader.js`, which implements the reading UI. The migration here is in
progress; much of the code still uses vanilla JS.
We also have some core utilities in `main.js`.
Future PRs will set up a proper build system, add unit tests, and
further clean up `reader.js`.
Test plan: experimented with all three interfaces on the dev
environment.
=> Add dictionary.js and further split up main.js

Makefile, ambuda/static/js/core.ts, ambuda/static/js/dictionary.js, ambuda/static/js/hamburger-button.js, ambuda/static/js/proofer.js, ambuda/static/js/reader.js, ambuda/static/js/sanscript.d.ts, ambuda/templates/texts/section.html, docs/installation.rst, docs/quickstart.rst, fabfile.py, package-lock.json, package.json, scripts/install_from_scratch.sh
Now we can run `make js_check_types` to type check our frontend code.
In addition, standardize our naming conventions for `make` commands and
fix a few small frontend regressions.
=> Add basic TypeScript setup

.github/workflows/basic-tests.yml
This will make sure we don't accidentally break readthedocs builds with a docs update.
=> Build docs on CI

ambuda/static/js/reader.js, ambuda/templates/texts/section.html
Fixes the following:
- Script menu always reverts to Devanagari (#181). This also affects
the text size dropdown and the parse layout dropdown.
- Transliteration also affects UI elements (#182).
Remaining regressions that still need fixing:
- Side-by-side layout is broken (#173). This is due to some CSS changes
in a parent element.
Test plan:
Manual testing. But now that our frontend application code is more
complex, it's time to add more robust testing tools for it. I'll do this
in a follow-up PR.
=> Fix various UI regressions

cli.py, config.py, scripts/install_from_scratch.sh
- Add SECRET_KEY to the `.env` file we generate during `make install` so
that the user doesn't have to define it manually.
- Create an initial build of our JS code both so that `flask run` works
and also so that we adequately test out esbuild during the install
process.
Test plan: ran these commands after deleting untracked files (`.env`,
database, `env`, `node_modules`).
=> Add secret key and JS build to install script

ambuda/queries.py, ambuda/static/js/main.js, ambuda/tasks/projects.py, cli.py, test/ambuda/tasks/test_projects_tasks.py
Now users can run `./cli.py create-project` to create a new proofing
project from a PDF. This command uses the same underlying logic that we
use on Celery, but it doesn't require any Celery or Redis setup.
Test plan: Unit tests and ran `/cli.py create-project` on a local PDF. I
also uploaded a PDF through the uploader on the devserver to confirm
that the Celery code still works normally.
=> Use Celery project uploader in cli.py

ambuda/__init__.py, ambuda/checks.py
This sanity check verifies that the data tables defined in the
application match the data tables defined in the database. Currently,
this code checks that:
- all app tables exist in the database
- a given app table and its corresponding database table have the same
column names.
Future PRs can add more extensive checks.
Test plan: ran the sanity check under the following conditions:
1. latest main (OK)
2. one column missing from a model (failed)
3. one model deleted (failed)
=> Add sanity check to validate database schemas

Makefile, scripts/install_from_scratch.sh
If `make install` detects files that indicate a previous install
attempt, abort the install and tell the user how to proceed.
Test plan: ran `make destructive-clean install` on the repo.
=> Add warning for make install on dirty repo

requirements.txt
Fixes https://github.com/ambuda-org/ambuda/issues/134. Installs cleanly with this fix.
=> Fix PyMuPDF version as 1.20.2

.github/workflows/basic-tests.yml
This will ensure that package.json and package-lock.json are both in sync with each other.
=> Update npm install -> npm ci in CI

ambuda/__init__.py, ambuda/templates/base.html, ambuda/templates/header-main-footer.html
As I was writing up a privacy policy in https://github.com/ambuda-org/ambuda/pull/169, I noticed a few things:
- unpkg doesn't have a privacy policy (see https://twitter.com/unpkg/status/1215718511537876992)
- we probably want to avoid loading as many third-party scripts as possible, for privacy reasons
So I switched from unpkg -> jsdelivr for the alpine script, and I also set up a CSP header that whitelists domains whose scripts can be loaded on our site. This also has the added bonus that inline javascript is disallowed by CSP, helping mitigate the risks of XSS attacks.
We'd probably eventually want to cut down on the number of external scripts and just get to `script-src 'self'` if possible, though.
=> Set up CSP, unpkg -> jsdelivr

ambuda/static/css/style.css, ambuda/templates/texts/section.html
Fixes https://github.com/ambuda-org/ambuda/issues/173. Basically, we needed to apply the `side-by-side` class to `#text--content` -- this way the CSS could expand its width so that there would be enough space to view the verses side by side.
=> Fix side-by-side view

ambuda/templates/about/people.html, ambuda/views/about.py
To recognize Ashwin's substantial and ongoing contributions to Ambuda, I'm
adding some information about him to our People page. "Core Engineering"
is a catch-all title for Ashwin's full-stack work, but we can always
change it later.
=> Add Ashwin to about.people

ambuda/__init__.py, ambuda/templates/header-main-footer.html
This reverts commit 86233b4af0ca900dbcb416e316e273d64a3de75c.
Context: CSP breaks inline CSS and JS in the proofing UI.
=> Revert "Set up CSP, unpkg -> jsdelivr"

ambuda/static/js/proofer.js, ambuda/templates/proofing/pages/edit.html, test/js/proofer.test.js
A flexible menu that transliterates between two arbitrary scripts.
To keep the tool user-friendly for now, I pared down the list to
remove schemes and encodings that seem less relevant.
Test plan: unit tests and ran the tool on dev.
=> Add transliteration menu

ambuda/static/css/style.css, ambuda/static/js/proofer.js, ambuda/templates/base.html, ambuda/templates/header-main-footer.html, ambuda/templates/proofing/pages/edit.html
The menu spports a variety of accented Latin characters and special
Devanagari characters. The menu looks a little crude but is workable for
now.
Test plan: used the menu on dev. A Jest test here would basically just
be testing the mock.
=> Add character select menu to proofer

ambuda/seed/dcs.py, ambuda/utils/cheda.py, ambuda/views/proofing/project.py, test/ambuda/utils/test_parsing.py, test/ambuda/views/proofing/test_project.py
This fixes the following causes of HTTP 500 errors:
- POST on an `edit` page redirects to a non-existing route
- `ashirlin` parse code is not recognized
- one of our parse data rows contains more than 3 columns. (Fixed
upstream)
Test plan: unit tests
=> Fix multiple production regressions

ambuda/templates/proofing/index.html, ambuda/templates/proofing/talk.html, ambuda/views/proofing/main.py, test/ambuda/views/proofing/test_main.py
Our discussion threads don't have a notifications mechanism, which
greatly reduces their usefulness. As a quick workaround, create a single
link that shows all discussion across all projects.
The implementation is a litle hacky, but we can refine if it this
becomes a popular feature.
Test plan: unit tests and opened the new page on the dev server.
=> Add page to see all proofing threads at once 

ambuda/seed/texts/gretil.py
Fixes #223
Corrected the following typos:
- From `amaruzakatam` to `amaruzatakam`
- From `bodhicAryAvatAraH` to `bodhicaryAvatAraH`
=> Fix typo in gretil seed script

ambuda/seed/dcs.py, ambuda/utils/cheda.py, test/ambuda/utils/test_parsing.py
- Seed script should check for exactly 3 fields, not exactly 3 `\t`
characters. (Fixes #255)
- `cheda` should also recognize `lan_unaug`
Test plan: unit tests and ran the seed script.
=> Fix a seed script error and 500 error

ambuda/filters.py, ambuda/static/js/proofer.js, ambuda/templates/proofing/complete-guidelines.html, ambuda/templates/proofing/editor-guide.html, ambuda/templates/proofing/pages/edit.html, ambuda/templates/proofing/pages/editor-components.html, ambuda/views/proofing/main.py, ambuda/views/proofing/page.py, test/ambuda/views/proofing/test_main.py
The page editor has become much more complex. This page describes how to
use it and what features it has available.
In addition, I moved all of our help pages to be under `/proofing/help`. I did so
because I had a local Flask error where Flask thought `editor-guide` was
a project slug and attempted to load the `project.summary` route
instead. (The error was resolved by using `/editor-guide2` or
`/editor-guide3`, but `/editor-guide` specifically fails. I'm not sure
why.) This issue suggests two potential problems going forward:
1. We should be careful about adding new slugs to the `proofing`
namespace since they can interact strangely with `project.summary`.
2. In fact, we should probably just namespace projects under a new
`projects` prefix. This is also avoids a potential issue where a …
=> Add user guide for page editor

ambuda/templates/proofing/pages/editor-components.html
Added `spellcheck=false` attribute to `<textarea>` to disable
spellcheck. Fixes #242
=> Remove spell check for Devanagari

ambuda/__init__.py, ambuda/templates/base.html, ambuda/templates/header-main-footer.html, ambuda/templates/proofing/pages/editor-components.html, ambuda/utils/assets.py
Cache busting means that when we update a file like `main.js`, we modify
the `main.js` URL in such a way that all users will fetch a new version
of the file. Without cache busting, users will use a stale version that
could be either degraded or broken.
Our URL scheme appends a simple query parameter based on a hash of the
asset's content.  On dev, these URLs have no effect. On prod, we will
hash the asset content at most once per application startup.
(A common cache busting solution is `webassets` via the Flask-Assets
package. But `webassets` doesn't cleanly interact with our live Tailwind
and esbuild watchers, which is why I avoid it here.)
Test plan: examined the generated URLs on the devserver.
(Fixes #62.)
=> Add cache busting for CSS and JS assets

ambuda/templates/support.html
At least one heading was rendered as ordinary text since it was outside
of the `prose` context.
Test plan: loaded the page on dev.
=> Fix headings on support page

requirements.txt
As suggested by dependabot. This also bumps `proto-plus`.
Test plan: ran OCR locally.
=> Bump google-cloud-vision from 2.7.3 to 3.1.1

ambuda/templates/macros/proofing-guides.html, ambuda/templates/macros/proofing.html, ambuda/templates/proofing/beginners-guide.html, ambuda/templates/proofing/complete-guide.html, ambuda/templates/proofing/create-project-post.html, ambuda/templates/proofing/create-project.html, ambuda/templates/proofing/editor-guide.html, ambuda/templates/proofing/recent-changes.html, ambuda/templates/proofing/tagging/index.html, ambuda/views/proofing/main.py
- Rename `complete-guidelines` to `complete-guide` for consistency.
- Switch to `title_and_subtitle` headings where feasible.
- Add illustrations to the beginners guide.
Test plan: unit tests and clicked around on dev.
=> Revise various proofing docs

ambuda/seed/texts/gretil.py, ambuda/utils/tei_parser.py, test/ambuda/utils/test_tei_parser.py
Major changes:
- The script is now idempotent. That is, running it over and over will
have the same impact on the database.
- The script won't delete existing texts. This prevents a previous rough
edge where running the seed script would delete all parse data in
prod.
- TEI parsing functions are now in `tei_parsing.py`, where we can reuse
them for future applications (other TEI upload scripts, uploading
through the website, etc.)
- The script has some basic unit tests.
Test plan: ran the script.
=> Make GRETIL seed script more reliable

Makefile, ambuda/checks.py, ambuda/seed/lookup/__main__.py, fabfile.py, scripts/install_from_scratch.sh
This command lets contributors sync with the latest production setup.
The command installs our latest Python and Node dependencies and also
upgrades the database by applying migrations and loading any new lookup
tables.
Test plan: ran the command.
=> Add `make upgrade` script

ambuda/views/proofing/main.py
The page is loading slowly for me in prod. Upon debugging, I found that
our current prod setup runs N+2 queries, where N is the number of
projects:
- 1 to fetch all projects
- N to fetch pages for each project
- 1 to fetch page statuses
Since we use sqlite, this isn't as bad as it seems. But even so, I
thought there was room to improve this query by fetching our data in one
trip and dropping extraneous fields.
Test plan: unit tests and ran the query on dev.
=> Optimize proofing.index query

ambuda/enums.py, ambuda/seed/lookup/page_status.py, ambuda/static/js/main.js, ambuda/static/js/sortable-list.js, ambuda/templates/proofing/index.html, ambuda/views/proofing/main.py, test/js/sortable-list.test.js
The UX isn't great, but this lets us sort a list of projects by:
- creation date
- total progress, measured as the number of red pages left.
Test plan: unit tests and tried the component on dev.
=> Add sorting options for project list

ambuda/templates/macros/proofing.html, ambuda/templates/proofing/index.html, ambuda/templates/proofing/talk.html, ambuda/templates/proofing/user/summary.html, test/ambuda/views/proofing/test_user.py
Examples:
- A user doesn't have a description.
- The proofing interface doesn't have any texts.
- There's no ongoing discussion.
=> Add placeholder text for empty queries 

ambuda/__init__.py, ambuda/checks.py, ambuda/enums.py
The moderator role is between an admin and a p2 proofer. Moderators will
be able to delete projects, ban users, promote users, and otherwise run
operations across the entire proofing effort.
This commit just defines the role without any additional functionality.
Future commits will grant the moderator express rights.
Fixes #298.
=> Add moderator role

ambuda/templates/macros/proofing.html, ambuda/templates/proofing/projects/activity.html, ambuda/templates/proofing/projects/edit.html, ambuda/templates/proofing/recent-changes.html, ambuda/templates/proofing/user/activity.html, ambuda/views/proofing/main.py, ambuda/views/proofing/project.py, ambuda/views/proofing/user.py
This updates our change logs to include information about created
projects. Our logs now include most kinds of proofing changes, and we
can add others (such as edits to project metadata) in the future.
=> Show created projects in logs

fabfile.py, test_prod.py
ambuda.org was down for about 8 hours.
Timeline
--------
- Arun runs `fab deploy` around midnight PST.
- The site goes down (nginx 502).
- Akshay notices around 12:10 am PST.
- Shreevatsa pings arun in the morning around 7 am PST.
- Arun brings the site back up.
Root cause
----------
PR https://github.com/ambuda-org/ambuda/pull/310 defines a new moderator role. The server check-fails if the role
isn't available. Our deploy script restarts the application but gives no
indication if the deploy is in a healthy state:
```
======================= 255 passed, 2 warnings in 10.40s =======================
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Restarting application ...
Restarting Celery task runner ... …
```
=> Add health checks for production deploy

ambuda/checks.py, ambuda/consts.py, ambuda/seed/lookup/__main__.py, ambuda/seed/lookup/create_bot_user.py, ambuda/static/js/html-poller.js, ambuda/static/js/main.js, ambuda/tasks/__init__.py, ambuda/tasks/ocr.py, ambuda/tasks/projects.py, ambuda/tasks/utils.py, ambuda/templates/include/ocr-progress.html, ambuda/templates/proofing/create-project-post.html, ambuda/templates/proofing/projects/batch-ocr-post.html, ambuda/templates/proofing/projects/batch-ocr.html, ambuda/templates/proofing/projects/edit.html, ambuda/utils/assets.py, ambuda/utils/google_ocr.py, ambuda/utils/revisions.py, ambuda/views/proofing/page.py, ambuda/views/proofing/project.py, cli.py, config.py, scripts/install_from_scratch.sh, test/ambuda/tasks/test_projects_tasks.py, test/ambuda/views/proofing/test_page.py
This lets us run batch OCR by clicking a link in a project's Edit tab.
The UX is poor, and the Celery setup needs more tuning to avoid blocking
PDF uploads. But it's better to ship something usable than wait on
getting every detail right.
Large changes:
- added `ambuda.tasks.ocr` to handle the batch OCR logic.
- added a `create_bot_user` seed script.
- moved some utilities from `tasks/projects.py` to `tasks/utils.py`.
- moved more utilities from `page.py` to `utils/revisions.py`.
Test plan:
- ran OCR for a new project
- ran OCR for a project where OCR has been run already
- existing unit tests
=> Add support for batch OCR

ambuda/seed/utils/itihasa_utils.py
The encoding of the page is UTF-8, even though somehow `requests` thinks that it's ISO-8859-1.
Other alternatives to this fix would be setting `resp.encoding = 'utf-8'` or using `resp.content.decode('utf-8')` instead of `resp.text`.
```
In [1]: import requests
In [2]: resp = requests.get('https://bombay.indology.info/ramayana/text/UD/Ram01.txt')
In [3]: resp.encoding
Out[3]: 'ISO-8859-1'
In [4]: resp.text?
Type:        property
String form: <property object at 0x104e985e0>
Docstring:  
Content of the response, in unicode.
If Response.encoding is None, encoding will be guessed using
``charset_normalizer`` or ``chardet``.
The encoding of the response content is determined based solely on HTTP
headers, following RFC 2616 to the letter. If you can take advantage of
non-HTTP knowledge to make …
```
=> Fix Unicode encoding

ambuda/views/proofing/main.py, ambuda/views/proofing/project.py, ambuda/views/proofing/user.py, test/ambuda/conftest.py
1. ambuda-bot's activity floods the "Recent changes" page and makes it
almost useless. For now, remove all changes by ambuda-bot so that
contributions by other users are more visible.
2. ambuda-bot has so many contributions in production that its Activity
page loads very slowly, even with an index. The root cause is an
unoptimized query. With a small fix, the page should be much more
performant.
3. ambuda-bot has so many contributions that its Activity page is a
little overwhelming. For now, show just the 100 most recent revisions
for a given user.
4. Fix a bug in "Recent changes" where the list of revisions + products
isn't properly truncated after the sort.
Test plan: tested all of these on the dev server.
=> Fix several small issues related to ambuda-bot

ambuda/static/js/reader.js
A previous commit added an overaggressive `e.preventDefault()` call
which disables all links on the reader, including navigation links.
Instead, we should call this function only for the specific link we
wish to disable.
Test plan: tested on dev.
=> Fix broken links in reader

ambuda/utils/google_ocr.py, test/ambuda/utils/test_google_ocr.py
The `import io` line was removed in https://github.com/ambuda-org/ambuda/pull/317 but wasn't caught in our tests.
Test plan: added a unit test and verified the fix on the dev server.
=> Fix broken page OCR

.readthedocs.yaml
The build uses an older Python version by default, which has recently caused the docs to break. Upgrading the Python version we use fixes the issue.
Test plan: created a doc build from this branch.
=> Fix readthedocs.io build

ambuda/templates/proofing/pages/edit.html, ambuda/views/proofing/page.py
These "buttons" are actually radiobutton labels, and clicking a label
selects the underlying radiobutton. By using Tailwind's `peer-checked:`
modifier, we can style a label if its radiobutton is selected.
Test plan: tried out the widget on the devserver.
=> Switch page status widget to buttons

ambuda/templates/header-main-footer.html, ambuda/templates/include/footer.html, ambuda/templates/include/header.html, ambuda/templates/index.html, ambuda/templates/texts/index.html
- Align menu bar items in `site.index` on mobile.
- Unify `site.index` header with other header logic.
- Define footer language links in a loop.
- Use English text headers in `texts.index`.
Test plan: unit tests.
=> Add various small UX tweaks

ambuda/views/site.py
I accidentally used `/contact` in my emails to potential translators.
But `/contact` raises a 404. Oops!
This is a more intuitive URL anyway, so perhaps we should just
standardize on it.
Test plan: tested on localhost.
=> Add support for `/contact` URL

ambuda/tasks/projects.py, ambuda/templates/macros/proofing.html, ambuda/templates/proofing/projects/activity.html, ambuda/templates/proofing/projects/admin.html, ambuda/templates/proofing/projects/batch-ocr-post.html, ambuda/templates/proofing/projects/batch-ocr.html, ambuda/templates/proofing/projects/download.html, ambuda/templates/proofing/projects/edit.html, ambuda/templates/proofing/projects/search.html, ambuda/templates/proofing/projects/summary.html, ambuda/templates/proofing/talk/board.html, ambuda/templates/proofing/talk/thread.html, ambuda/views/proofing/project.py, cli.py, test/ambuda/conftest.py, test/ambuda/tasks/test_projects_tasks.py, test/ambuda/views/proofing/test_project.py
This extends our project admin panel to moderators. Currently, we do
hard deletes, but we can implement soft deletes in the future.
Test plan: tested this functionality on dev.
=> Allow moderators to delete projects

test/ambuda/conftest.py, test/ambuda/views/proofing/test_user.py, test/ambuda/views/test_auth.py
I used my own username as a placeholder when writing these tests, but I don't like the message this sends to contributors, as Ambuda is bigger than any one person.
I use `u-admin` as a placeholder to make this user's role clear, and I avoided variants like `admin-user` to avoid confusion with the `user` and `users` strings that appear in other contexts.
Test plan: unit tests pass.
=> Genericize admin username in tests

ambuda/templates/include/footer.html, ambuda/templates/index.html, ambuda/templates/macros/components.html, ambuda/translations/sa/LC_MESSAGES/messages.po
This uses the latest translation file from Transifex. Most of the text on Ambuda, excluding long documents, is now available in Sanskrit.
I also made the language select widget more visible on the main page.
Test plan: tried the language on dev.
=> Add latest Sanskrit translation file

ambuda/templates/blog/base.html, ambuda/templates/blog/create-post.html, ambuda/templates/blog/delete-post.html, ambuda/templates/blog/edit-post.html, ambuda/templates/blog/index.html, ambuda/templates/blog/post.html, ambuda/views/blog.py
This amends the previous commit to add Markdown parsing. Along the way, fix various small UI problems:
- Make `flash` success messages green.
- Add missing page titles.
- Tweak heading CSS.
Test plan: unit tests and experimented on dev.
=> Add Markdown filter for blog posts

Makefile, migrations/versions/99379162619e_add_user_statuses.py
- Upgrade schemas before trying to seed. Otherwise, a schema change causes the seed scripts to fail.
- Fix the down revision in the latest migration so that migration history is linear.
=> Fix DB upgrade in deploy script

ambuda/scripts/fetch_i18n_files.py
`distutils.dir_util` is deprecated and is missing on the server.
Test plan: ran the script locally and on prod.
=> Use shutil in i18n install script

ambuda/consts.py, ambuda/templates/texts/section.html, ambuda/views/reader/texts.py
A *single-section* text is a text with no major divisions -- no kaandas, no sargas, etc. Internally, we represent such texts as texts with a single section with the slug `"all"`.
Our current reader UI displays this `"all"` slug as if it's a valid identifier, which is unsightly. So as a fix, show the section slug only if the text has multiple sections.
Test plan: clicked around on dev
Before:
After:
=> Fix bug: single-section texts show "all" in nav

ambuda/static/js/dictionary.js, ambuda/static/js/routes.js, ambuda/templates/dictionaries/index.html, test/js/dictionary.test.js, test/js/routes.test.js
If the dictionary URL ends with "/apte/deva", update the dictionary app so that its dictionary menu shows `apte` and its query field shows `deva`.
Test plan: unit tests and ran on dev.
=> Update dictionary state using URL data

ambuda/static/js/sortable-list.js, ambuda/templates/proofing/index.html
Our proofers have requested more tools to search and manage the list of available projects. This commit adds a simple text form that performs case-insensitive substring matching against the list of projects.
The implementation itself is quite clumsy since it manages state in both JS data and in the order and attributes of HTML elements. I think this messy approach is acceptable given that this is a new feature and the actual logic is quite short. If our proofers ask for other filtering options in the future, we can clean this up.
Test plan: tried it on dev.
=> [proofing] Add filter field for project list

ambuda/templates/dictionaries/index.html, ambuda/templates/macros/dictionaries.html
This was accidentally set to the empty string while pushing out multi-dict support for the reader.
Test plan: tried it on dev.
=> [bug] Redefine x-model for dictionary sources

ambuda/templates/macros/proofing.html, ambuda/templates/proofing/beginners-guide.html, ambuda/templates/proofing/complete-guide.html, ambuda/templates/proofing/create-project.html, ambuda/templates/proofing/dashboard.html, ambuda/templates/proofing/editor-guide.html, ambuda/templates/proofing/index.html, ambuda/templates/proofing/projects/activity.html, ambuda/templates/proofing/projects/admin.html, ambuda/templates/proofing/projects/batch-ocr-post.html, ambuda/templates/proofing/projects/batch-ocr.html, ambuda/templates/proofing/projects/download.html, ambuda/templates/proofing/projects/edit.html, ambuda/templates/proofing/projects/search.html, ambuda/templates/proofing/projects/summary.html, ambuda/templates/proofing/recent-changes.html, ambuda/templates/proofing/stats.html, ambuda/templates/proofing/tagging/index.html, ambuda/templates/proofing/talk.html, ambuda/templates/proofing/talk/board.html, ambuda/templates/proofing/talk/create-post.html, ambuda/templates/proofing/talk/create-thread.html, ambuda/templates/proofing/talk/thread.html, ambuda/templates/proofing/user/activity.html, ambuda/templates/proofing/user/admin.html, ambuda/templates/proofing/user/edit.html, ambuda/templates/proofing/user/summary.html, ambuda/views/proofing/main.py
This is a simple starting point for a more feature-rich dashboard that
will let moderators manage the proofing effort as a whole.
Test plan: unit tests and tried it on dev.
=> [proofing] Add moderator dashboard

ambuda/static/js/core.ts, test/js/core.test.js
The root cause was a bug in `transliterateHTMLString`. This has been fixed.
Test plan: new unit tests and tried it on dev.
=> [bug] Use user script for padaccheda

Makefile
Fix two bugs:
1. Our deploy process fetches `.po` files but doesn't compile them.
2. The default `pybabel` command skips files marked `flaky`.
See `Makefile` comments for details.
Test plan: ran some version of this on prod.
=> [i18n] Fix build command

Makefile, scripts/run_devserver_docker.sh
This file is large, and downloading it on each PR push puts undue burden on a third-party server that isn't designed for a CI use case.
Test plan: run on GitHub.
=> [infra] Avoid MW download in Docker CI test

ambuda/templates/proofing/create-project-post.html, ambuda/templates/proofing/create-project.html
Before the upload, explicitly ask for the title as it appears in the printed book.
After upload, emphasize that uploads will continue in the background even
if the tab is closed.
=> [proofing] Add various help text

ambuda/templates/macros/components.html, ambuda/templates/proofing/pages/edit.html, ambuda/templates/proofing/pages/editor-components.html, ambuda/views/proofing/page.py
We want users to use OCR if they need to, but we don't want them to re-run OCR on an edited page. We also have less need for the prominent "Run OCR" button now that we have batch OCR.
New UX: If a page has no edits, show the user a help box prompting them to run OCR. If a page has edits already, hide the help box. OCR is always available under the `Tools` menu if it's really needed.
Test plan: unit tests and tried it on dev.
=> [proofing] Hide OCR button for pages with edits

ambuda/templates/macros/components.html, ambuda/templates/proofing/pages/edit.html, test/ambuda/views/proofing/test_page.py
A few users have tried making changes, clicked submit, and found that their changes were lost. A proper flow here will prompt login and save user changes. But for now, just hide the button and add another warning.
Test plan: unit tests and tried it on dev.
=> [proofing] Hide proofing button for unauth users

ambuda/__init__.py, ambuda/database.py, ambuda/static/css/style.css, ambuda/static/js/reader.js, ambuda/static/js/sortable-list.js, ambuda/templates/htmx/text-block.html, ambuda/templates/include/script-options.html, ambuda/templates/texts/section.html, ambuda/utils/json_serde.py, ambuda/utils/xml.py, ambuda/views/proofing/main.py, ambuda/views/proofing/tagging.py, ambuda/views/reader/texts.py, ambuda/views/site.py, test/ambuda/utils/test_json_serde.py, test/ambuda/utils/test_xml.py, test/js/reader.test.js
This commit refactors our reader code to better make use of Alpine. The changes here impose a simple reactive dataflow where the source of truth is whatever is stored on the Alpine application object.
The reader.js code is manageable but just barely so. The current data model makes it difficult to reason about the application state and write tests. By doing more of the heavy lifting in Alpine and its reactive data model, we can simplify several parts of the code while maintaining the same functionality and making it easier to build new features.
HTML:
- Use `x-cloak`, `template`, and other Alpine devices to more compactly describe JS-specific logic.
- Include serialized JSON data in `texts/section.html`, which we use to initiaiize the Alpine app.
- Move various HTML fragments from …
=> [reader] Refactor reader.js

ambuda/templates/texts/section.html
Set an explicit width to prevent ugly rendering of long lines on mobile.
Test plan: tried it on dev.
Before:
After:
=> [reader] Fix long text rendering on mobile

docs/creating-data-from-the-command-line.rst, docs/installation.rst, docs/quickstart.rst, scripts/install_from_scratch.sh
=> Fix typo in installation.rst (start-docker -> docker-start)

ambuda/templates/proofing/projects/edit.html, ambuda/templates/proofing/projects/replace.html, ambuda/views/proofing/project.py
* reset fork to upstream HEAD to address https://github.com/ambuda-org/ambuda/pull/452#issuecomment-1434178057
* re-applied changes for proofing project-wide `replace` words feature
1. built container with make docker-start
2. checked Texts, Dictionaries, and Proofing pages.
3. tested `proofing > project > edit > search` page
4. tested `proofing > project > edit > search and replace` page
1. Test actual `search and replace`. I could not find a pre-existing text in db to test this feature.
2. add support in translation files
=> [proofing] Add partial work for search+replace
