ambuda-org/ambuda

Makefile
docs/installation.rst

Also update the dev docs to reflect the need for this variable setting
and how it's done in the make command.

Export Flask Environment Variable in Make Command

---

docs/architecture.rst

Hopefully this is the right way to link using sphinx?

Link to "principles" doc for "principle (2)" language

---

.gitignore

Add __pycache__ to gitignore as git was trying to pick up a bunch of files within these directories.

Add __pycache__ to gitignore

---

ambuda/seed/texts/gretil.py
docs/quickstart.rst

https://github.com/ambuda-org/ambuda/pull/84 and https://github.com/ambuda-org/ambuda/pull/81

Various doc fixes

---

ambuda/seed/utils/itihasa_utils.py

Fixes https://github.com/ambuda-org/ambuda/issues/96. In the future, we should really add itihasa / gretil import to CI to ensure they don't accidentally break...

fix itihasa import

---

Makefile
ambuda/auth.py
ambuda/models/auth.py
ambuda/tasks/projects.py
ambuda/utils/proofing_utils.py
ambuda/views/proofing/main.py
ambuda/views/proofing/pages.py
test/ambuda/conftest.py
test/ambuda/tasks/test_projects_tasks.py
test/ambuda/test_auth_manager.py
test/ambuda/test_models.py
test/ambuda/utils/test_proofing_utils.py
test/ambuda/views/proofing/test_main.py
test/ambuda/views/proofing/test_pages.py
test/ambuda/views/test_site.py

Going forward, I'd like our project coverage to be no lower than 80%,
with 100% coverage for all views.

Increase backend test coverage to 80%

---

.github/workflows/basic-tests.yml

Follow up to https://github.com/ambuda-org/ambuda/pull/105

Enforce 80% backend test coverage on CI

---

Makefile
docs/quickstart.rst
package-lock.json
package.json

Fixes https://github.com/ambuda-org/ambuda/issues/111

Run tailwind_watcher concurrently when running "make devserver"

---

fabfile.py

These were missing before, which would cause the script to fail. Also,
add some print statements to better convey the deploy status.

Add virtualenv checks to fabfile

---

ambuda/static/css/style.css
ambuda/static/js/proofreading.js
ambuda/templates/proofing/pages/edit.html

In addition:
- add `Layout` option to support top-and-bottom view.
- add `Mark text` option to mark up text.

Migrate proofing interface to Alpine

---

.eslintrc.js
ambuda/static/js/proofreading.js
ambuda/templates/proofing/pages/edit.html

This doesn't interact very well with manual zooming, but for now this is
still an improvement.
Test plan: experimented locally.

Remember zoom preferences in proofing UI

---

ambuda/static/js/main.js

Fixes https://github.com/ambuda-org/ambuda/issues/143, tested locally.

Fix proper transliteration of dictionary entries

---

Makefile
ambuda/static/js/core.js
ambuda/static/js/dictionary.js
ambuda/static/js/hamburger-button.js
ambuda/static/js/main.js
ambuda/static/js/proofer.js
ambuda/static/js/reader.js
ambuda/static/js/routes.js
ambuda/templates/dictionaries/index.html
ambuda/templates/header-main-footer.html
ambuda/templates/proofing/pages/edit.html
ambuda/templates/texts/section.html
fabfile.py
package-lock.json
package.json

This unlocks a lot of good stuff, including:
- bundling
- minifying
- namespaces
- tree shaking
- better integrations with eslint
- TypeScript
Test plan: tried the reader, proofer, and dictionary tool on the
devserver.

Build JavaScript with esbuild

---

ambuda/views/proofing/main.py
ambuda/views/proofing/pages.py
ambuda/views/proofing/utils.py
test/ambuda/utils/test_proofing_utils.py
test/ambuda/views/proofing/test_pages.py
test/ambuda/views/reader/test_cheda.py

In addition, clean up some unused imports.

Add various backend tests

---

ambuda/utils/google_ocr.py
test/ambuda/utils/test_google_ocr.py

fixes https://github.com/ambuda-org/ambuda/issues/153. Post processing around:
- danda and double danda
- remove curly quotes

Add OCR post-processing

---

ambuda/templates/about/terms.html
ambuda/templates/include/footer.html
ambuda/views/about.py

Add terms of use.
Partially based on https://foundation.wikimedia.org/wiki/Terms_of_Use/en
For https://github.com/ambuda-org/ambuda/issues/127

Add terms of use

---

cli.py
docs/architecture.rst
docs/creating-data-from-the-command-line.rst
docs/index.rst
docs/installation.rst
docs/managing-the-database.rst
docs/project-layout.rst
docs/quickstart.rst
docs/running-in-production.rst

- Update docs around `make db-seed-basic`.
- Add note on Alpine.js.
- Make the CLI docs more obvious.
- Fix various typos.

Update docs to reflect project changes

---

ambuda/xml.py

This approach is more flexible and allows us to perform more
sophisticated transforms on the input element.
Test plan: unit tests

Use function-based API for XML rules

---

Makefile
ambuda/static/js/core.ts
ambuda/static/js/dictionary.js
ambuda/static/js/proofer.js
ambuda/static/js/reader.js
ambuda/templates/dictionaries/index.html
ambuda/templates/proofing/pages/edit.html
ambuda/templates/texts/section.html
jest.config.js
test/js/core.test.js
test/js/dictionary.test.js
test/js/proofer.test.js
test/js/reader.test.js

With a few basic mocks, we can test almost all of our frontend code.

Increase Jest coverage minimum to 50%

---

.github/workflows/basic-tests.yml

Fixes https://github.com/ambuda-org/ambuda/issues/256

Fix docker CI

---

ambuda/tasks/__init__.py
docker-compose.yml

Uploads now work locally when running `make start-docker`!

Run redis and celery with docker-compose

---

ambuda/static/css/style.css
ambuda/templates/proofing/user.html
ambuda/utils/heatmap.py
ambuda/views/proofing/users.py
tailwind.config.js
test/ambuda/utils/test_heatmap.py

Just for fun.
Test plan: unit tests and ran on synthetic data in dev:

Create user contribution heatmap

---

ambuda/__init__.py
ambuda/seed/lookup/page_status.py
ambuda/seed/lookup/role.py
ambuda/seed/utils/cdsl_utils.py
ambuda/tasks/projects.py
ambuda/utils/google_ocr.py
config.py

- Pickup log config from app config
- Update logger config of root/default logger given in python logging module (which is what will be used for logging) 
Running the devserver and then hitting the `/admin` endpoint without signing in.
```
(env) Akshay at MacBook-Pro-85 in ~/ambuda on logs*
$ make devserver 
npx concurrently "flask run" "make tailwind_watcher"
[1] npx tailwindcss -i ./ambuda/static/css/style.css -o ./ambuda/static/gen/style.css --watch
[0]  * Serving Flask app "ambuda:create_app('development')" (lazy loading)
[0]  * Environment: development
[0]  * Debug mode: on
[1] 
[1] Rebuilding...
[1] Done in 962ms.
[0]  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
[0]  * Restarting with watchdog (fsevents)
[0]  * Debugger is active!
[0]  * Debugger PIN: 119-223-396
[0] …
```

Add logger

---

ambuda/consts.py
ambuda/seed/texts/gretil.py
ambuda/views/reader/texts.py

Add catuhsloki

---

tailwind.config.js

Otherwise, we miss some classes.

Fix proofing glob path in Tailwind config

---

ambuda/static/js/reader.js

Fixes #307.
Test plan: tested on dev.

Fix bug: clicking "Show original" scrolls to top

---

ambuda/templates/proofing/pages/editor-components.html

Fixes #306.
Test plan: tested on dev.

Fix bug: warn on unsaved change is inconsistent

---

ambuda/views/proofing/project.py
test/ambuda/views/proofing/test_project.py

There's an import error in prod.
Test plan: added a unit test and tested on dev.

Fix bug: project activity raises server error

---

ambuda/templates/texts/section.html

This is trivial with Alpine. Alpine's default is a fade/rescale
transition, which I found a little disorienting. So instead I chose a
simple fade.
Test plan: tried it on dev.
Fixes #18.

Add sidebar transition

---

ambuda/templates/proofing/pages/editor-components.html

This adapts #252 and cleans up the UI.
Test plan: tried the feature.

Add OPTITRANS support

---

docs/i18n-and-l10n.rst

Update our i18n docs with details on our current process, including how
we use Transifex.

Update i18n docs

---

ambuda/scripts/analysis/ramayana.py
ambuda/scripts/analysis/single_file_text.py
ambuda/seed/dcs.py
ambuda/seed/dictionaries/apte.py
ambuda/seed/dictionaries/monier.py
ambuda/seed/dictionaries/shabdakalpadruma.py
ambuda/seed/dictionaries/shabdartha_kaustubha.py
ambuda/seed/dictionaries/shabdasagara.py
ambuda/seed/dictionaries/vacaspatyam.py
ambuda/seed/lookup/create_bot_user.py
ambuda/seed/lookup/page_status.py
ambuda/seed/lookup/role.py
ambuda/seed/texts/gretil.py
ambuda/seed/texts/mahabharata.py
ambuda/seed/texts/ramayana.py
ambuda/seed/utils/data_utils.py
ambuda/seed/utils/itihasa_utils.py
cli.py
migrations/versions/6c87b647ecaa_add_page_statuses.py

I added this option to just the `shabdartha_kaustubha` since it has new
upstream data we want to fetch. We can lazily add this option to our
other seed scripts as needed, but they tend to be more stable or have a
Git fetch built-in.
In addition, I moved some functions in `itihasa_utils.py` into a new
module `data_utils.py`.
Test plan: ran the script.

Add option to read latest data in seed scripts

---

ambuda/utils/proofing_utils.py

Minor code change: I was reading this file and got a bit confused by all the "str"s everywhere; giving them some more specific names made them easier to read.
(I have another pending PR which will change all this :P But in the meantime I think this may be an improvement…)

Give more specific names to some str types

---

ambuda/README.md
ambuda/models/README.md
ambuda/seed/README.md
ambuda/static/README.md
ambuda/tasks/README.md
ambuda/templates/README.md
ambuda/translations/README.md
ambuda/utils/README.md
ambuda/views/README.md
test/README.md

Copied some descriptions from the docs/ and left the rest blank, but hopefully we can improve them in future.
While https://ambuda.readthedocs.io/en/latest/ exists as "top-down" or "from the outside in" documentation, I think there's also value in having "bottom-up" or "from the inside out" documentation closer to the code, in the form of a README.md in each directory.
Ideally it would describe the "interface" of the code in that directory ("module"): where it fits in the bigger picture / its slot in the "map" of the project architecture.
I've populated whatever was obvious to me, and can take suggestions for the rest, or we can merge this and improve incrementally.

Add a README.md to most directories.

---

ambuda/seed/dictionaries/apte_sanskrit_hindi.py
ambuda/seed/utils/cdsl_utils.py
ambuda/templates/about/code-and-data.html
ambuda/templates/include/dict-options.html
ambuda/utils/xml.py
ambuda/views/dictionaries.py

See file comments for details.
Test plan: loaded on dev.

Add Apte Sanskrit-Hindi dictionary

---

ambuda/static/css/style.css
ambuda/static/js/dictionary.js
ambuda/templates/dictionaries/index.html
test/js/dictionary.test.js

The history widget shows the user's last 10 queries. When a query in the history is clicked, the app displays the results for that query.
Test plan: ran on dev.

Add dictionary history widget

---

ambuda/static/js/reader.js

If the user clicks on a verse and the app can't make a connection to the server, the verse disappears. This commit fixes the bug. A future change should improve the UX here and notify the user that something has gone wrong.
Test plan: tried it in dev.

[bug] Fix disappearing verse on network error

---

ambuda/templates/about/people.html

To recognize Kishore's substantial and ongoing contributions to Ambuda, I'm adding some information about him to our People page. "Core Engineering" is a catch-all title for Kishore's full-stack work, but we can always change it later.

[site] Add Kishore to about.people

---

.eslintrc.js
ambuda/static/js/reader.js
ambuda/templates/texts/section.html

This fixes a bug introduced in the previous commit. I missed the bug
because I refactored some code after testing on the website and unit
tests still passed.
Test plan: tried it on dev. I'll add more robust tests in the future.

[reader] Fix "Show original" behavior bug

---

ambuda/static/css/style.css
ambuda/static/js/reader.js
ambuda/templates/htmx/text-block.html
ambuda/templates/texts/section.html
ambuda/utils/xml.py
ambuda/views/proofing/tagging.py
ambuda/views/reader/schema.py
ambuda/views/reader/texts.py
test/ambuda/utils/test_xml.py
test/js/reader.test.js

This commit also prepares us for Ajax navigation, which needs a little
more work.
Test plan: unit tests and clicked around on dev.

[reader] Transliterate text and section title

---

Dockerfile

Using caching / img optimization techniques

Decrease docker image size from 1.65GB -> 1.54GB

---

ambuda/consts.py

[i18n] Add support for Hindi
